version: '3'

services:
  app:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html

  db:
    image: postgres:latest
    ports:
      - '15432:5432'
    env_file:
      - ./env/db.env
    environment:
      PGDATA: /var/lib/postgresql/data/phpisdead/
    volumes:
      - dbdata:/var/lib/postgresql/data/
    depends_on:
      - app
      - phpfpm

volumes:
  dbdata:

